import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useMemo } from 'react';

const Layout = ({ children }: {
  children: React.ReactNode
}) => {

  const route = usePathname()
  const pages = [
    {
      name: 'Create',
      path: "/create"
    },
    {
      name: 'Grab',
      path: "/grab"
    }
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Red Envelope DApp</title>
        <meta
          content="Generated by murong"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header className='py-4 w-full flex justify-center'>
        <ConnectButton />
      </header>

      <main className="flex flex-col items-center mt-10">
        <div role="tablist" className="tabs tabs-boxed">
          {
            pages.map((page) => (
              <Link href={page.path} key={page.name} role="tab" className={`tab ${route === page.path ? 'tab-active' : ''}`}>
                {page.name}
              </Link>
            ))
          }
        </div>
        {children}
      </main>
    </div>
  );
};

export default Layout;
